export interface Tribe {
  id: string
  name: string
  region: string
  territories: string[]
  timelineStart: number
  timelineEnd: number | null
  population: string
  languages: string[]
  description: string
  traditions: string[]
  historicalEvents: { year: number; event: string }[]
  coordinates: { lat: number; lng: number }
  imageQuery: string
}

const regionMeta = {
  Southwest: { color: "#cd5c5c", position: { x: 22, y: 58 } },
  Southeast: { color: "#8b4513", position: { x: 72, y: 62 } },
  "Great Plains": { color: "#daa520", position: { x: 45, y: 42 } },
  Northeast: { color: "#2d5a27", position: { x: 82, y: 28 } },
  "Great Lakes": { color: "#4682b4", position: { x: 65, y: 30 } },
  "Northern Plains": { color: "#6b8e23", position: { x: 38, y: 22 } },
  "Pacific Northwest": { color: "#1f6f8b", position: { x: 18, y: 24 } },
  California: { color: "#c26d2f", position: { x: 18, y: 52 } },
  Plateau: { color: "#a0522d", position: { x: 26, y: 30 } },
  "Great Basin": { color: "#b56576", position: { x: 30, y: 46 } },
  Arctic: { color: "#0ea5e9", position: { x: 10, y: 10 } },
}

export const regionColors: Record<string, string> = Object.fromEntries(
  Object.entries(regionMeta).map(([region, meta]) => [region, meta.color]),
) as Record<string, string>

export const regionPositions: Record<string, { x: number; y: number }> = Object.fromEntries(
  Object.entries(regionMeta).map(([region, meta]) => [region, meta.position]),
) as Record<string, { x: number; y: number }>

export const tribes: Tribe[] = [
  {
    id: "navajo",
    name: "Navajo (Diné)",
    region: "Southwest",
    territories: ["Arizona", "New Mexico", "Utah", "Colorado"],
    timelineStart: 1400,
    timelineEnd: null,
    population: "~400,000",
    languages: ["Navajo", "English"],
    description:
      "The Navajo Nation is the largest Native American tribe in the United States. Known as Diné, meaning 'The People,' they have inhabited the Four Corners region for centuries. Their rich culture includes intricate weaving, silversmithing, and sand painting traditions.",
    traditions: ["Sand Painting", "Rug Weaving", "Silversmithing", "Kinaalda Ceremony"],
    historicalEvents: [
      { year: 1864, event: "The Long Walk to Bosque Redondo" },
      { year: 1868, event: "Treaty of Bosque Redondo signed" },
      { year: 1923, event: "Navajo Nation Council established" },
    ],
    coordinates: { lat: 36.0672, lng: -109.188 },
    imageQuery: "navajo monument valley desert landscape",
  },
  {
    id: "cherokee",
    name: "Cherokee",
    region: "Southeast",
    territories: ["North Carolina", "Tennessee", "Georgia", "Oklahoma"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~370,000",
    languages: ["Cherokee", "English"],
    description:
      "The Cherokee are one of the indigenous peoples of the Southeastern Woodlands. They developed their own writing system, the Cherokee syllabary, created by Sequoyah. Despite the tragedy of the Trail of Tears, the Cherokee Nation thrives today as a sovereign nation.",
    traditions: ["Stomp Dance", "Basket Weaving", "Pottery", "Green Corn Ceremony"],
    historicalEvents: [
      { year: 1821, event: "Sequoyah completes Cherokee syllabary" },
      { year: 1838, event: "Trail of Tears forced relocation" },
      { year: 1839, event: "Cherokee Nation established in Oklahoma" },
    ],
    coordinates: { lat: 35.9132, lng: -84.864 },
    imageQuery: "smoky mountains cherokee land forest",
  },
  {
    id: "sioux",
    name: "Sioux (Lakota, Dakota, Nakota)",
    region: "Great Plains",
    territories: ["South Dakota", "North Dakota", "Montana", "Nebraska", "Minnesota"],
    timelineStart: 1300,
    timelineEnd: null,
    population: "~170,000",
    languages: ["Lakota", "Dakota", "Nakota", "English"],
    description:
      "The Great Sioux Nation, comprising the Lakota, Dakota, and Nakota people, are renowned warriors and buffalo hunters of the Great Plains. Their spiritual traditions, including the Sun Dance, remain central to their cultural identity.",
    traditions: ["Sun Dance", "Vision Quest", "Sweat Lodge", "Buffalo Hunt"],
    historicalEvents: [
      { year: 1868, event: "Treaty of Fort Laramie" },
      { year: 1876, event: "Battle of Little Bighorn" },
      { year: 1890, event: "Wounded Knee Massacre" },
    ],
    coordinates: { lat: 43.8554, lng: -102.3397 },
    imageQuery: "black hills south dakota prairie plains",
  },
  {
    id: "apache",
    name: "Apache",
    region: "Southwest",
    territories: ["Arizona", "New Mexico", "Texas", "Oklahoma"],
    timelineStart: 1300,
    timelineEnd: null,
    population: "~111,000",
    languages: ["Apache languages", "English"],
    description:
      "The Apache are a group of culturally related Native American tribes in the Southwestern United States. Known for their fierce resistance to Spanish and American expansion, legendary leaders like Geronimo and Cochise led their people with unwavering courage.",
    traditions: ["Sunrise Ceremony", "Crown Dance", "Wickiup Building", "Storytelling"],
    historicalEvents: [
      { year: 1861, event: "Cochise leads Apache resistance" },
      { year: 1886, event: "Geronimo surrenders" },
      { year: 1913, event: "Apache prisoners of war released" },
    ],
    coordinates: { lat: 33.3942, lng: -109.8872 },
    imageQuery: "apache desert mountains arizona",
  },
  {
    id: "iroquois",
    name: "Iroquois (Haudenosaunee)",
    region: "Northeast",
    territories: ["New York", "Pennsylvania", "Ohio", "Ontario", "Quebec"],
    timelineStart: 1142,
    timelineEnd: null,
    population: "~125,000",
    languages: ["Mohawk", "Oneida", "Onondaga", "Cayuga", "Seneca", "Tuscarora", "English"],
    description:
      "The Haudenosaunee, or 'People of the Longhouse,' formed one of the world's oldest participatory democracies. The Iroquois Confederacy's Great Law of Peace influenced the United States Constitution and continues to govern the Six Nations today.",
    traditions: ["Longhouse Ceremonies", "False Face Society", "Lacrosse", "Wampum Diplomacy"],
    historicalEvents: [
      { year: 1142, event: "Formation of the Iroquois Confederacy" },
      { year: 1722, event: "Tuscarora join as sixth nation" },
      { year: 1794, event: "Treaty of Canandaigua" },
    ],
    coordinates: { lat: 42.8864, lng: -76.5183 },
    imageQuery: "finger lakes new york forest autumn",
  },
  {
    id: "choctaw",
    name: "Choctaw",
    region: "Southeast",
    territories: ["Mississippi", "Alabama", "Louisiana", "Oklahoma"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~200,000",
    languages: ["Choctaw", "English"],
    description:
      "The Choctaw Nation is one of the Five Civilized Tribes. They were the first to walk the Trail of Tears. During the Irish Potato Famine, despite their own hardships, the Choctaw people sent aid to Ireland—a gesture of compassion remembered to this day.",
    traditions: ["Stickball", "Social Dancing", "Basket Weaving", "Choctaw Code Talkers"],
    historicalEvents: [
      { year: 1830, event: "Indian Removal Act signed" },
      { year: 1831, event: "First to walk Trail of Tears" },
      { year: 1918, event: "Choctaw Code Talkers serve in WWI" },
    ],
    coordinates: { lat: 34.7304, lng: -95.9569 },
    imageQuery: "mississippi woodland native forest",
  },
  {
    id: "seminole",
    name: "Seminole",
    region: "Southeast",
    territories: ["Florida", "Oklahoma"],
    timelineStart: 1700,
    timelineEnd: null,
    population: "~18,000",
    languages: ["Creek", "Mikasuki", "English"],
    description:
      "The Seminole emerged as a distinct people in Florida, welcoming escaped slaves and other refugees. They are the only tribe never to sign a peace treaty with the United States, earning them the name 'The Unconquered.'",
    traditions: ["Green Corn Dance", "Patchwork Clothing", "Chickee Building", "Alligator Wrestling"],
    historicalEvents: [
      { year: 1817, event: "First Seminole War begins" },
      { year: 1835, event: "Second Seminole War—Osceola leads resistance" },
      { year: 1957, event: "Seminole Tribe of Florida federally recognized" },
    ],
    coordinates: { lat: 26.1901, lng: -80.3659 },
    imageQuery: "florida everglades swamp wetlands",
  },
  {
    id: "ojibwe",
    name: "Ojibwe (Anishinaabe)",
    region: "Great Lakes",
    territories: ["Michigan", "Wisconsin", "Minnesota", "North Dakota", "Ontario", "Manitoba"],
    timelineStart: 1400,
    timelineEnd: null,
    population: "~170,000",
    languages: ["Ojibwe", "English"],
    description:
      "The Ojibwe are one of the largest Indigenous groups in North America. Masters of birch bark canoe construction and wild rice harvesting, they are keepers of the sacred Midewiwin Lodge and the Seven Fires Prophecy.",
    traditions: ["Wild Rice Harvesting", "Birch Bark Canoes", "Midewiwin Ceremonies", "Dreamcatcher Making"],
    historicalEvents: [
      { year: 1837, event: "Treaty of St. Peters" },
      { year: 1854, event: "Treaty of La Pointe" },
      { year: 1999, event: "Supreme Court affirms treaty rights" },
    ],
    coordinates: { lat: 46.8772, lng: -89.3126 },
    imageQuery: "great lakes forest birch trees autumn",
  },
  {
    id: "crow",
    name: "Crow (Apsáalooke)",
    region: "Great Plains",
    territories: ["Montana", "Wyoming"],
    timelineStart: 1600,
    timelineEnd: null,
    population: "~13,000",
    languages: ["Crow", "English"],
    description:
      "The Apsáalooke, meaning 'Children of the Large-Beaked Bird,' are skilled horsemen and buffalo hunters of the Northern Plains. Their culture emphasizes warrior traditions, clan systems, and the preservation of their homeland in Montana.",
    traditions: ["Crow Fair", "Sweat Lodge", "Vision Quest", "Beadwork"],
    historicalEvents: [
      { year: 1825, event: "First Crow Treaty" },
      { year: 1868, event: "Fort Laramie Treaty" },
      { year: 1904, event: "Crow Act reduces reservation" },
    ],
    coordinates: { lat: 45.605, lng: -107.46 },
    imageQuery: "montana mountains bighorn canyon",
  },
  {
    id: "hopi",
    name: "Hopi",
    region: "Southwest",
    territories: ["Arizona"],
    timelineStart: 500,
    timelineEnd: null,
    population: "~18,000",
    languages: ["Hopi", "English"],
    description:
      "The Hopi, whose name means 'peaceful people,' have continuously inhabited their mesa villages for over a thousand years, making Old Oraibi one of the oldest continuously inhabited settlements in North America. Their rich ceremonial life includes the Kachina traditions.",
    traditions: ["Kachina Ceremonies", "Snake Dance", "Pottery Making", "Dry Farming"],
    historicalEvents: [
      { year: 1540, event: "First contact with Spanish explorers" },
      { year: 1680, event: "Pueblo Revolt" },
      { year: 1882, event: "Hopi Reservation established" },
    ],
    coordinates: { lat: 35.8781, lng: -110.4144 },
    imageQuery: "hopi mesa arizona desert pueblo",
  },
  {
    id: "blackfeet",
    name: "Blackfeet (Niitsitapi)",
    region: "Northern Plains",
    territories: ["Montana", "Alberta"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~35,000",
    languages: ["Blackfoot", "English"],
    description:
      "The Blackfeet Confederacy, known as Niitsitapi or 'The Real People,' are renowned warriors and buffalo hunters whose territory once stretched from the Rocky Mountains to the Saskatchewan River. Their sacred Backbone of the World (Rocky Mountains) remains central to their spirituality.",
    traditions: ["Sun Dance", "Medicine Bundle Ceremonies", "Buffalo Jumps", "Tipi Artistry"],
    historicalEvents: [
      { year: 1855, event: "Lame Bull Treaty" },
      { year: 1870, event: "Marias Massacre" },
      { year: 1910, event: "Glacier National Park created from Blackfeet lands" },
    ],
    coordinates: { lat: 48.6667, lng: -112.8833 },
    imageQuery: "glacier national park montana mountains",
  },
  {
    id: "pueblo",
    name: "Pueblo Peoples",
    region: "Southwest",
    territories: ["New Mexico", "Arizona"],
    timelineStart: 100,
    timelineEnd: null,
    population: "~60,000",
    languages: ["Keres", "Tewa", "Tiwa", "Towa", "Zuni", "English", "Spanish"],
    description:
      "The Pueblo peoples comprise 19 distinct communities in New Mexico and Arizona. Their ancestors built the magnificent cliff dwellings of Mesa Verde and Chaco Canyon. Today, they maintain vibrant cultures centered on corn agriculture and ceremonial traditions.",
    traditions: ["Corn Ceremonies", "Pottery", "Feast Days", "Kiva Rituals"],
    historicalEvents: [
      { year: 1598, event: "Spanish colonization begins" },
      { year: 1680, event: "Pueblo Revolt expels Spanish" },
      { year: 1924, event: "Pueblo Lands Act" },
    ],
    coordinates: { lat: 35.5972, lng: -106.0713 },
    imageQuery: "taos pueblo adobe new mexico",
  },
  {
    id: "wampanoag",
    name: "Wampanoag",
    region: "Northeast",
    territories: ["Massachusetts", "Rhode Island", "Marthas Vineyard"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~5,000",
    languages: ["Wopanaak", "English"],
    description:
      "The Wampanoag Confederacy have stewarded the shores of southeastern New England for thousands of years, surviving epidemics, war, and displacement while preserving their identity and reclaiming their language.",
    traditions: ["Clambakes", "Wampum Crafting", "Quahog Shell Carving", "Strawberry Thanksgiving"],
    historicalEvents: [
      { year: 1621, event: "Alliance and shared harvest with Plymouth settlers" },
      { year: 1675, event: "King Philip's War devastates Wampanoag homelands" },
      { year: 1993, event: "Wopanaak Language Reclamation Project begins immersive teaching" },
    ],
    coordinates: { lat: 41.9001, lng: -70.7167 },
    imageQuery: "cape cod atlantic shoreline wampanoag homelands",
  },
  {
    id: "muscogee",
    name: "Muscogee (Creek)",
    region: "Southeast",
    territories: ["Alabama", "Georgia", "Florida", "Oklahoma"],
    timelineStart: 900,
    timelineEnd: null,
    population: "~90,000",
    languages: ["Muscogee", "English"],
    description:
      "The Muscogee, or Este Mvskokvlke, are descendants of the Mississippian mound builders and one of the historic Five Civilized Tribes. Despite forced removal, they rebuilt a sovereign nation in Indian Territory and maintain vibrant ceremonial grounds.",
    traditions: ["Stomp Dance", "Green Corn Ceremony", "Ribbon Skirts", "Stickball"],
    historicalEvents: [
      { year: 1836, event: "Second Creek War leads to mass removals along the Trail of Tears" },
      { year: 1866, event: "Reconstruction Treaty affirms Muscogee sovereignty in Indian Territory" },
      { year: 1971, event: "Modern Muscogee Nation constitution ratified" },
    ],
    coordinates: { lat: 35.3771, lng: -96.926 },
    imageQuery: "oklahoma river valley muscogee nation homelands",
  },
  {
    id: "nez-perce",
    name: "Nez Perce (Nimiipuu)",
    region: "Plateau",
    territories: ["Idaho", "Oregon", "Washington"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~3,500",
    languages: ["Nez Perce", "English"],
    description:
      "The Nimiipuu, or Nez Perce, are Plateau horse people renowned for breeding the Appaloosa and for their deep salmon traditions. They maintained seasonal rounds across the Columbia Plateau and resisted forced removal with courage and strategy.",
    traditions: ["Appaloosa Horse Breeding", "Salmon Fishing", "Tamkaliks Celebration", "Root Digs"],
    historicalEvents: [
      { year: 1855, event: "Treaty of Walla Walla recognizes a vast Nez Perce homeland" },
      { year: 1877, event: "Nez Perce War and 1,170-mile flight toward Canada" },
      { year: 1986, event: "Nez Perce National Historic Trail established" },
    ],
    coordinates: { lat: 46.321, lng: -116.922 },
    imageQuery: "idaho canyonland rolling hills nez perce territory",
  },
  {
    id: "tlingit",
    name: "Tlingit",
    region: "Pacific Northwest",
    territories: ["Southeast Alaska", "Yukon"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~16,000",
    languages: ["Tlingit", "English"],
    description:
      "The Tlingit are maritime people of Southeast Alaska whose clan houses, totem poles, and Chilkat weaving reflect a sophisticated matrilineal society tied to salmon, cedar, and the sea.",
    traditions: ["Clan House Potlatches", "Chilkat Weaving", "Cedar Canoe Carving", "Raven and Eagle Stories"],
    historicalEvents: [
      { year: 1741, event: "First sustained contact with Russian traders" },
      { year: 1867, event: "Alaska Purchase shifts colonial control to the United States" },
      { year: 1971, event: "Alaska Native Claims Settlement Act establishes regional corporations" },
    ],
    coordinates: { lat: 57.0531, lng: -135.33 },
    imageQuery: "southeast alaska fjords spruce rainforest tlingit territory",
  },
  {
    id: "haida",
    name: "Haida",
    region: "Pacific Northwest",
    territories: ["Haida Gwaii", "Prince of Wales Island"],
    timelineStart: 700,
    timelineEnd: null,
    population: "~4,500",
    languages: ["Haida", "English"],
    description:
      "The Haida are famed carvers and navigators of the North Pacific, known for monumental cedar poles, ocean-going canoes, and deep stewardship of the islands they call Haida Gwaii.",
    traditions: ["Totem Pole Carving", "Argillite Sculpture", "Cedar Bark Weaving", "Potlatch Feasts"],
    historicalEvents: [
      { year: 1787, event: "Maritime fur trade brings intensified outside contact" },
      { year: 1862, event: "Smallpox epidemics decimate Haida communities" },
      { year: 1993, event: "Gwaii Haanas Agreement creates co-management with Canada" },
    ],
    coordinates: { lat: 53.253, lng: -132.072 },
    imageQuery: "haida gwaii islands cedar forest totem poles coastline",
  },
  {
    id: "yurok",
    name: "Yurok",
    region: "California",
    territories: ["Klamath River", "Redwood Coast", "Northern California"],
    timelineStart: 900,
    timelineEnd: null,
    population: "~6,300",
    languages: ["Yurok", "English"],
    description:
      "The Yurok people live along the Klamath River and Pacific Coast, guided by salmon cycles and redwood forests. They maintain ceremonies that restore balance between people, river, and ocean.",
    traditions: ["Salmon Ceremony", "Brush Dance", "Canoe Building", "Basketry"],
    historicalEvents: [
      { year: 1855, event: "Klamath River Reservation established" },
      { year: 1910, event: "Fishing rights conflicts intensify along the Klamath" },
      { year: 1988, event: "Hoopa-Yurok Settlement Act reaffirms reservation boundaries" },
    ],
    coordinates: { lat: 41.527, lng: -124.055 },
    imageQuery: "klamath river redwood forest mist yurok land",
  },
  {
    id: "ute",
    name: "Ute",
    region: "Great Basin",
    territories: ["Colorado", "Utah", "Wyoming", "New Mexico"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~11,000",
    languages: ["Ute", "English"],
    description:
      "The Ute people have long ranged across the Rocky Mountains and Great Basin, adapting between foothills, plateaus, and plains while maintaining deep horse traditions and the Bear Dance.",
    traditions: ["Bear Dance", "Powwow Drumming", "Beadwork", "Horse Culture"],
    historicalEvents: [
      { year: 1868, event: "Treaty establishes several Ute reservations in Colorado and Utah" },
      { year: 1879, event: "Meeker Incident triggers forced removal from Colorado homelands" },
      { year: 1934, event: "Indian Reorganization Act enables modern Ute tribal governments" },
    ],
    coordinates: { lat: 40.3, lng: -109.99 },
    imageQuery: "colorado plateau high desert mountains ute lands",
  },
  {
    id: "pawnee",
    name: "Pawnee",
    region: "Great Plains",
    territories: ["Nebraska", "Kansas", "Oklahoma"],
    timelineStart: 900,
    timelineEnd: null,
    population: "~3,500",
    languages: ["Pawnee", "English"],
    description:
      "The Pawnee are Caddoan-speaking Plains people once living in large earth lodge towns along Nebraska rivers. Their sky knowledge, farming, and buffalo hunts shaped seasonal life.",
    traditions: ["Buffalo Dance", "Earth Lodge Ceremonies", "Star Stories", "Beadwork"],
    historicalEvents: [
      { year: 1857, event: "Treaties cede most Pawnee homelands in Nebraska" },
      { year: 1875, event: "Pawnee forced relocation to Indian Territory" },
      { year: 1936, event: "Pawnee Nation reorganizes government under the IRA" },
    ],
    coordinates: { lat: 36.337, lng: -97.0 },
    imageQuery: "prairie plains nebraska kansas sky pawnee homelands",
  },
  {
    id: "lumbee",
    name: "Lumbee",
    region: "Southeast",
    territories: ["North Carolina"],
    timelineStart: 1700,
    timelineEnd: null,
    population: "~55,000",
    languages: ["English"],
    description:
      "The Lumbee of North Carolina are one of the largest tribes east of the Mississippi, with roots among Siouan, Algonquian, and African ancestors. They maintain a unique dialect and culture despite incomplete federal recognition.",
    traditions: ["Lumbee Homecoming", "Pinecone Patchwork", "Gospel Singing", "Cultural Pageants"],
    historicalEvents: [
      { year: 1885, event: "North Carolina formally recognizes the Lumbee" },
      { year: 1956, event: "Lumbee Act acknowledges the tribe without full federal services" },
      { year: 1958, event: "Lumbee citizens repel the Ku Klux Klan at Hayes Pond" },
    ],
    coordinates: { lat: 34.6929, lng: -79.0092 },
    imageQuery: "north carolina pine forests lumbee homeland",
  },
  {
    id: "tohono-oodham",
    name: "Tohono O'odham",
    region: "Southwest",
    territories: ["Arizona", "Sonoran Desert"],
    timelineStart: 300,
    timelineEnd: null,
    population: "~34,000",
    languages: ["Tohono O'odham", "English"],
    description:
      "The Tohono O'odham, Desert People of the Sonoran borderlands, sustained vibrant communities through dry farming, saguaro harvesting, and salt pilgrimages even as a border split their homelands.",
    traditions: ["Saguaro Wine Ceremony", "Basketry", "Desert Dry Farming", "Salt Pilgrimage"],
    historicalEvents: [
      { year: 1853, event: "Gadsden Purchase divides O'odham homelands" },
      { year: 1916, event: "Papago Reservation established (later Tohono O'odham Nation)" },
      { year: 1986, event: "Name formally restored to Tohono O'odham Nation" },
    ],
    coordinates: { lat: 32.0401, lng: -111.8883 },
    imageQuery: "sonoran desert saguaros tohono oodham lands",
  },
  {
    id: "zuni",
    name: "Zuni (A:shiwi)",
    region: "Southwest",
    territories: ["New Mexico"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~12,000",
    languages: ["Zuni", "English"],
    description:
      "The A:shiwi people have lived along the Zuni River for millennia, renowned for dryland farming, inlay jewelry, and the sacred mesa Dowa Yalanne that anchors their cultural life.",
    traditions: ["Shalako Ceremony", "Inlay Jewelry", "Dryland Farming", "Pottery"],
    historicalEvents: [
      { year: 1540, event: "Coronado's entrada meets Zuni at Hawikku" },
      { year: 1877, event: "Zuni Reservation established in western New Mexico" },
      { year: 1990, event: "NAGPRA supports return of Zuni Ahayu:da (War Gods)" },
    ],
    coordinates: { lat: 35.0722, lng: -108.8484 },
    imageQuery: "zuni pueblo mesas new mexico sunrise",
  },
  {
    id: "osage",
    name: "Osage",
    region: "Great Plains",
    territories: ["Missouri", "Arkansas", "Kansas", "Oklahoma"],
    timelineStart: 900,
    timelineEnd: null,
    population: "~20,000",
    languages: ["Osage", "English"],
    description:
      "The Wahzhazhe (Osage) people are a Dhegiha Siouan nation who moved west to the tallgrass prairies, later rebuilding sovereignty and wealth in Oklahoma after forced removals and the painful Reign of Terror.",
    traditions: ["Inlonshka Dances", "Wahzhazhe Songs", "Finger Weaving", "Hominy Dishes"],
    historicalEvents: [
      { year: 1808, event: "Treaty of Fort Clark cedes Missouri River homelands" },
      { year: 1872, event: "Osage forced removal to Indian Territory" },
      { year: 1921, event: "Oil boom and Osage Reign of Terror spur federal investigations" },
    ],
    coordinates: { lat: 36.667, lng: -96.337 },
    imageQuery: "tallgrass prairie osage hills oklahoma",
  },
  {
    id: "cheyenne",
    name: "Cheyenne",
    region: "Great Plains",
    territories: ["Montana", "Wyoming", "Oklahoma"],
    timelineStart: 1600,
    timelineEnd: null,
    population: "~23,000",
    languages: ["Cheyenne", "English"],
    description:
      "The Cheyenne, Algonquian speakers of the Plains, include the Northern Cheyenne and the Cheyenne and Arapaho Tribes, keepers of the Sacred Arrows and resilient survivors of massacres and removals.",
    traditions: ["Sun Dance", "Sacred Arrows Ceremony", "Ledger Art", "Powwow Songs"],
    historicalEvents: [
      { year: 1864, event: "Sand Creek Massacre kills Cheyenne and Arapaho villagers" },
      { year: 1876, event: "Cheyenne join at Little Bighorn victory" },
      { year: 1878, event: "Northern Cheyenne Exodus back toward homelands" },
    ],
    coordinates: { lat: 45.627, lng: -106.667 },
    imageQuery: "northern plains montana prairie cheyenne homeland",
  },
  {
    id: "comanche",
    name: "Comanche (Numunuu)",
    region: "Great Plains",
    territories: ["Texas", "Oklahoma", "New Mexico", "Colorado"],
    timelineStart: 1700,
    timelineEnd: null,
    population: "~17,000",
    languages: ["Comanche", "English"],
    description:
      "The Comanche, or Numunuu, rose as master horse people of the Southern Plains, shaping the era of Comancheria before war, treaties, and allotment confined their range.",
    traditions: ["Horse Culture", "Flute Music", "Beadwork", "Numunuu Language Revitalization"],
    historicalEvents: [
      { year: 1867, event: "Medicine Lodge Treaty sets reservation boundaries" },
      { year: 1874, event: "Red River War undermines Comanche autonomy" },
      { year: 1901, event: "Allotment opens Kiowa-Comanche-Apache lands to settlement" },
    ],
    coordinates: { lat: 34.603, lng: -98.395 },
    imageQuery: "southern plains red river prairie comanche country",
  },
  {
    id: "lenape",
    name: "Lenape (Delaware)",
    region: "Northeast",
    territories: ["Delaware", "New Jersey", "Pennsylvania", "Oklahoma"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~20,000",
    languages: ["Lenape", "English"],
    description:
      "The Lenape, original peoples of the Delaware River valley, were pushed west by colonial pressure yet maintain vibrant communities in Oklahoma, Wisconsin, and Ontario while keeping stories of the Lenapehoking homeland.",
    traditions: ["Big House Ceremony", "Wampum Belts", "Riverine Fishing", "Storytelling"],
    historicalEvents: [
      { year: 1682, event: "Treaty of Shackamaxon with William Penn" },
      { year: 1737, event: "Walking Purchase forces large land cessions" },
      { year: 1867, event: "Delaware sign agreement to relocate within Cherokee Nation in Indian Territory" },
    ],
    coordinates: { lat: 39.95, lng: -75.16 },
    imageQuery: "delaware river forests lenape homelands",
  },
  {
    id: "coast-salish",
    name: "Coast Salish",
    region: "Pacific Northwest",
    territories: ["Washington", "British Columbia", "Salish Sea"],
    timelineStart: 500,
    timelineEnd: null,
    population: "~65,000",
    languages: ["Lushootseed", "Hul'q'umi'num'", "English"],
    description:
      "Coast Salish nations across the Salish Sea are cedar and salmon people with deep village networks, longhouses, and resurgent canoe journeys linking families from Puget Sound to Vancouver Island.",
    traditions: ["Cedar Canoe Journeys", "Longhouse Gatherings", "Wool Weaving", "Salmon Ceremonies"],
    historicalEvents: [
      { year: 1855, event: "Treaty of Point Elliott signed with Puget Sound nations" },
      { year: 1974, event: "Boldt Decision affirms treaty fishing rights" },
      { year: 1989, event: "Modern Tribal Canoe Journeys revive intertribal ocean travel" },
    ],
    coordinates: { lat: 48.0, lng: -122.3 },
    imageQuery: "salish sea cedar forests islands coast salish territory",
  },
  {
    id: "chumash",
    name: "Chumash",
    region: "California",
    territories: ["Central California Coast", "Channel Islands"],
    timelineStart: 500,
    timelineEnd: null,
    population: "~5,500",
    languages: ["Chumashan languages", "English"],
    description:
      "The Chumash are maritime peoples of the Santa Barbara Channel, renowned for plank canoes (tomols), shell bead currency, and rock art connecting coastal villages with the islands.",
    traditions: ["Tomol Canoe Voyages", "Basketry", "Rock Art", "Bead Currency"],
    historicalEvents: [
      { year: 1542, event: "First contact with Juan Rodríguez Cabrillo's expedition" },
      { year: 1824, event: "Chumash Uprising challenges mission rule" },
      { year: 2001, event: "Tomol crossings to Limuw (Santa Cruz Island) are renewed annually" },
    ],
    coordinates: { lat: 34.4208, lng: -119.6982 },
    imageQuery: "channel islands pacific coast chumash homelands",
  },
  {
    id: "shoshone-bannock",
    name: "Shoshone-Bannock",
    region: "Great Basin",
    territories: ["Idaho", "Wyoming", "Nevada", "Utah"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~6,000",
    languages: ["Shoshoni", "English"],
    description:
      "The Shoshone-Bannock Tribes of Fort Hall continue traditions of buffalo harvests, salmon and camas gathering, and the handgame while navigating treaties that constrained their vast homelands.",
    traditions: ["Sun Dance", "Buffalo Harvest", "Beadwork", "Handgame"],
    historicalEvents: [
      { year: 1863, event: "Fort Bridger Treaty establishes boundaries for Shoshone-Bannock bands" },
      { year: 1900, event: "Fort Hall Reservation boundaries finalized by federal order" },
      { year: 1964, event: "Indian Claims Commission settlement addresses land losses" },
    ],
    coordinates: { lat: 42.87, lng: -112.45 },
    imageQuery: "sagebrush plateau fort hall idaho shoshone bannock",
  },
  {
    id: "inupiat",
    name: "Inupiat",
    region: "Arctic",
    territories: ["Arctic Alaska", "North Slope"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~20,000",
    languages: ["Inupiaq", "English"],
    description:
      "The Inupiat of Alaska's Arctic coast are sea ice people whose lifeways revolve around bowhead whale hunts, caribou, and communal drumming that sustain villages across the tundra.",
    traditions: ["Whaling Festivals", "Inupiaq Drumming", "Caribou Hunting", "Seal Skin Crafting"],
    historicalEvents: [
      { year: 1972, event: "North Slope Borough home rule strengthens local governance" },
      { year: 1977, event: "Trans-Alaska Pipeline begins operations across Iñupiat lands" },
      { year: 1980, event: "ANILCA protects subsistence rights and Arctic homelands" },
    ],
    coordinates: { lat: 71.29, lng: -156.76 },
    imageQuery: "arctic alaska sea ice tundra inupiat village",
  },
  {
    id: "yupik",
    name: "Yup'ik (Central Alaskan Yup'ik)",
    region: "Arctic",
    territories: ["Western Alaska", "Yukon-Kuskokwim Delta"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~25,000",
    languages: ["Central Alaskan Yup'ik", "English"],
    description:
      "The Yup'ik of western Alaska are salmon and seal people whose qasgiq (communal house) life, dance masks, and subsistence cycles remain central despite epidemics and colonial pressure.",
    traditions: ["Mask Carving", "Qasgiq Ceremonies", "Salmon Fishing", "Seal Hunting"],
    historicalEvents: [
      { year: 1919, event: "Influenza pandemic devastates coastal villages" },
      { year: 1971, event: "Alaska Native Claims Settlement Act shapes village corporations" },
      { year: 1980, event: "ANILCA affirms subsistence protections in Alaska" },
    ],
    coordinates: { lat: 61.579, lng: -165.4 },
    imageQuery: "yukon kuskokwim delta tundra river alaska yupik community",
  },
  {
    id: "tsimshian",
    name: "Tsimshian",
    region: "Pacific Northwest",
    territories: ["Southeast Alaska", "British Columbia"],
    timelineStart: 800,
    timelineEnd: null,
    population: "~12,000",
    languages: ["Sm'algyax", "English"],
    description:
      "The Tsimshian people are matrilineal coastal nations known for carved poles, formline art, and clan feasts that link villages along the Pacific in Alaska and British Columbia.",
    traditions: ["Formline Carving", "Feasts and Potlatches", "Cedar Weaving", "Drum Songs"],
    historicalEvents: [
      { year: 1862, event: "Smallpox epidemics impact Tsimshian villages" },
      { year: 1887, event: "Community relocates to Annette Islands (New Metlakatla)" },
      { year: 1891, event: "Annette Islands Reserve established by U.S. for Tsimshian of Metlakatla" },
    ],
    coordinates: { lat: 55.129, lng: -131.574 },
    imageQuery: "annette island rainforest pacific northwest tsimshian territory",
  },
  {
    id: "abenaki",
    name: "Abenaki",
    region: "Northeast",
    territories: ["Vermont", "New Hampshire", "Quebec"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~10,000",
    languages: ["Abenaki", "English", "French"],
    description:
      "The Abenaki are Wabanaki people of the northern woodlands, living between the Green Mountains and the St. Lawrence, known for birch bark canoes, sweetgrass baskets, and maple traditions.",
    traditions: ["Birch Bark Canoes", "Sweetgrass Basketry", "Maple Sugaring", "Wampum Crafting"],
    historicalEvents: [
      { year: 1759, event: "French and Indian War disperses many Abenaki communities" },
      { year: 1976, event: "Odanak and Wôlinak Abenaki councils strengthen cultural programs" },
      { year: 2011, event: "State recognition affirmed for Abenaki tribes in Vermont" },
    ],
    coordinates: { lat: 44.5588, lng: -72.5778 },
    imageQuery: "vermont green mountains forest abenaki homeland",
  },
  {
    id: "catawba",
    name: "Catawba",
    region: "Southeast",
    territories: ["South Carolina", "North Carolina"],
    timelineStart: 1000,
    timelineEnd: null,
    population: "~3,300",
    languages: ["English", "reviving Catawba"],
    description:
      "The Catawba Nation of the Carolina Piedmont are river people famed for their clay pottery, rebuilding sovereignty after land loss and a long fight to restore federal recognition.",
    traditions: ["Catawba Pottery", "River Ceremonies", "Beadwork", "Storytelling"],
    historicalEvents: [
      { year: 1840, event: "Treaty of Nation Ford dramatically reduces Catawba land base" },
      { year: 1959, event: "Termination of federal status" },
      { year: 1993, event: "Federal recognition restored to the Catawba Nation" },
    ],
    coordinates: { lat: 34.936, lng: -80.94 },
    imageQuery: "catawba river south carolina piedmont forest",
  },
  {
    id: "potawatomi",
    name: "Potawatomi",
    region: "Great Lakes",
    territories: ["Michigan", "Indiana", "Wisconsin", "Kansas", "Oklahoma"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~30,000",
    languages: ["Potawatomi", "English"],
    description:
      "The Potawatomi, Keepers of the Fire among the Anishinaabe, maintained villages around the Great Lakes before removals west; today multiple sovereign Potawatomi nations steward culture and land.",
    traditions: ["Black Ash Basketry", "Sugar Bush Camps", "Powwows", "Language Revitalization"],
    historicalEvents: [
      { year: 1833, event: "Treaty of Chicago cedes homelands and paves way for removal" },
      { year: 1838, event: "Potawatomi Trail of Death forced march to Kansas" },
      { year: 1861, event: "Citizen Potawatomi reorganize under a new constitution" },
    ],
    coordinates: { lat: 41.68, lng: -86.25 },
    imageQuery: "great lakes woodland shoreline potawatomi homelands",
  },
  {
    id: "paiute",
    name: "Paiute",
    region: "Great Basin",
    territories: ["Nevada", "Utah", "California"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~17,000",
    languages: ["Northern Paiute", "Southern Paiute", "English"],
    description:
      "Paiute peoples of the Great Basin are expert irrigators and gatherers of pine nuts, seeds, and roots across deserts and alpine valleys, navigating treaties and water conflicts.",
    traditions: ["Pine Nut Harvests", "Basketry", "Handgame", "Irrigated Agriculture"],
    historicalEvents: [
      { year: 1860, event: "Pyramid Lake War erupts over resources and encroachment" },
      { year: 1889, event: "Walker River and Pyramid Lake reservations formalized" },
      { year: 1934, event: "Indian Reorganization Act supports Paiute tribal governments" },
    ],
    coordinates: { lat: 39.5, lng: -118.5 },
    imageQuery: "great basin desert mountains nevada paiute lands",
  },
  {
    id: "kiowa",
    name: "Kiowa",
    region: "Great Plains",
    territories: ["Oklahoma", "Texas", "Kansas"],
    timelineStart: 1700,
    timelineEnd: null,
    population: "~12,000",
    languages: ["Kiowa", "English"],
    description:
      "The Kiowa are renowned Plains horse people and allies of the Comanche, keepers of the Ten Grandmother Sun Dance poles and ledger art traditions.",
    traditions: ["Gourd Dance", "Sun Dance", "Ledger Art", "Beadwork"],
    historicalEvents: [
      { year: 1867, event: "Medicine Lodge Treaty assigns Kiowa-Comanche-Apache reservation" },
      { year: 1874, event: "Red River War forces confinement to reservation" },
      { year: 1936, event: "Kiowa business committee formed under the IRA era" },
    ],
    coordinates: { lat: 34.982, lng: -98.389 },
    imageQuery: "red river plains oklahoma kiowa homeland",
  },
  {
    id: "akimel-oodham",
    name: "Akimel O'odham (Gila River)",
    region: "Southwest",
    territories: ["Arizona", "Gila River Valley"],
    timelineStart: 300,
    timelineEnd: null,
    population: "~23,000",
    languages: ["Akimel O'odham", "English"],
    description:
      "The Akimel O'odham, River People of the Gila, engineered canals and farming systems that sustained desert life, later forming the Gila River Indian Community with Maricopa neighbors.",
    traditions: ["Canal Irrigation", "Basketry", "Desert Farming", "Himdag (Way of Life)"],
    historicalEvents: [
      { year: 1853, event: "Gadsden Purchase shifts borders across O'odham lands" },
      { year: 1859, event: "Gila River Reserve established by U.S. authorities" },
      { year: 1939, event: "Gila River Indian Community constitution adopted" },
    ],
    coordinates: { lat: 33.17, lng: -111.89 },
    imageQuery: "gila river desert irrigation arizona akimel oodham",
  },
  {
    id: "puyallup",
    name: "Puyallup",
    region: "Pacific Northwest",
    territories: ["Washington", "Puget Sound"],
    timelineStart: 1200,
    timelineEnd: null,
    population: "~6,000",
    languages: ["Lushootseed", "English"],
    description:
      "The Puyallup are salmon and cedar people of the southern Salish Sea, signatories to the Medicine Creek Treaty and central to modern fishing rights victories.",
    traditions: ["Salmon Ceremonies", "Cedar Carving", "Canoe Journeys", "Lushootseed Language"],
    historicalEvents: [
      { year: 1854, event: "Medicine Creek Treaty signed with Puyallup and neighboring nations" },
      { year: 1974, event: "Boldt Decision affirms Puyallup treaty fishing rights" },
      { year: 1990, event: "Puyallup Land Claims Settlement Act compensates and restores land" },
    ],
    coordinates: { lat: 47.2, lng: -122.29 },
    imageQuery: "puget sound tideflats evergreen forests puyallup territory",
  },
]

export const regions = Object.entries(regionMeta).map(([region, meta]) => ({
  id: region.toLowerCase().replace(/\s+/g, "-"),
  name: region,
  color: meta.color,
}))

export function getTribesByRegion(region: string): Tribe[] {
  return tribes.filter((tribe) => tribe.region.toLowerCase().includes(region.toLowerCase()))
}

export function getTribeById(id: string): Tribe | undefined {
  return tribes.find((tribe) => tribe.id === id)
}
